Repository kubeflow/notebooks, pull requests merged in 2024-12, with the labels that each got.

#137 chore: update go linting + update dependencies for controller
  workspaces/backend/.gitignore
  workspaces/backend/.golangci.yml
  workspaces/backend/Dockerfile
  workspaces/backend/Makefile
  workspaces/backend/api/app.go
  workspaces/backend/api/errors.go
  workspaces/backend/api/healthcheck__handler_test.go
  workspaces/backend/api/namespaces_handler.go
  workspaces/backend/api/namespaces_handler_test.go
  workspaces/backend/api/suite_test.go
  workspaces/backend/api/workspacekinds_handler.go
  workspaces/backend/api/workspacekinds_handler_test.go
  workspaces/backend/api/workspaces_handler.go
  workspaces/backend/api/workspaces_handler_test.go
  workspaces/backend/go.mod
  workspaces/backend/go.sum
  workspaces/backend/internal/models/health_check.go
  workspaces/backend/internal/models/namespaces.go
  workspaces/backend/internal/models/workspacekinds.go
  workspaces/backend/internal/models/workspaces.go
  workspaces/backend/internal/repositories/health_check.go
  workspaces/backend/internal/repositories/namespaces.go
  workspaces/backend/internal/repositories/repositories.go
  workspaces/backend/internal/repositories/workspacekinds.go
  workspaces/backend/internal/repositories/workspaces.go
  workspaces/backend/internal/server/server.go
  workspaces/controller/.golangci.yml
  workspaces/controller/Dockerfile
  workspaces/controller/Makefile
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/cmd/main.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/config/rbac/role.yaml
  workspaces/controller/go.mod
  workspaces/controller/go.sum
  workspaces/controller/internal/controller/suite_test.go
  workspaces/controller/internal/controller/workspace_controller.go
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
  workspaces/controller/internal/helper/graph.go
  workspaces/controller/internal/helper/helper.go
  workspaces/controller/internal/helper/index.go
  workspaces/controller/internal/helper/template.go
  workspaces/controller/internal/webhook/suite_test.go
  workspaces/controller/internal/webhook/workspace_webhook.go
  workspaces/controller/internal/webhook/workspacekind_webhook.go
  workspaces/controller/internal/webhook/workspacekind_webhook_test.go
  workspaces/controller/test/e2e/e2e_suite_test.go
  workspaces/controller/test/e2e/e2e_test.go
  workspaces/controller/test/utils/utils.go
Labels: approved, lgtm, size/XXL

#140 feat(ws): Notebooks 2.0 // Frontend // Workspaces table // Live mockup
  workspaces/frontend/.prettierignore
  workspaces/frontend/.prettierrc
  workspaces/frontend/config/stylePaths.js
  workspaces/frontend/config/webpack.common.js
  workspaces/frontend/config/webpack.dev.js
  workspaces/frontend/config/webpack.prod.js
  workspaces/frontend/jest.config.js
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/__tests__/cypress/cypress.config.ts
  workspaces/frontend/src/__tests__/cypress/cypress/pages/home.ts
  workspaces/frontend/src/__tests__/cypress/cypress/pages/pageNotFound.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/AppRoutes.tsx
  workspaces/frontend/src/app/pages/Dashboard/Dashboard.tsx
  workspaces/frontend/src/app/pages/Settings/Settings.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/app/pages/notFound/NotFound.tsx
  workspaces/frontend/src/index.tsx
  workspaces/frontend/src/shared/types.ts
  workspaces/frontend/src/typings.d.ts
  workspaces/frontend/tsconfig.json
Labels: approved, lgtm, size/XXL

#141 chore(ws): Setup eslint and jest configurations
  workspaces/frontend/.eslintignore
  workspaces/frontend/.eslintrc
  workspaces/frontend/jest.config.js
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/index.tsx
Labels: approved, lgtm, size/XXL

#39 test(ws): enhance e2e test setup and cleanup
  .github/workflows/controller-tests.yaml
  workspaces/controller/Makefile
  workspaces/controller/test/e2e/e2e_suite_test.go
  workspaces/controller/test/e2e/e2e_test.go
  workspaces/controller/test/utils/utils.go
Labels: approved, lgtm, size/L

#158 ci: add action to enforce semantic PR titles
  .github/workflows/semantic-prs.yaml
Labels: approved, size/M, lgtm
