Repository kubeflow/notebooks, pull requests merged in 2024-11, with the labels that each got.

#72 Proposing to add myself as owner of frontend directory
  workspaces/frontend/OWNERS
Labels: approved, lgtm, size/XS

#73 chore(ws): add cypress structure and initial tests for frontend
  workspaces/frontend/.env.cypress.mock
  workspaces/frontend/README.md
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/__tests__/cypress/.gitignore
  workspaces/frontend/src/__tests__/cypress/cypress.config.ts
  workspaces/frontend/src/__tests__/cypress/cypress/pages/home.ts
  workspaces/frontend/src/__tests__/cypress/cypress/pages/pageNotFound.ts
  workspaces/frontend/src/__tests__/cypress/cypress/support/commands/axe.ts
  workspaces/frontend/src/__tests__/cypress/cypress/support/commands/index.ts
  workspaces/frontend/src/__tests__/cypress/cypress/support/e2e.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
  workspaces/frontend/src/__tests__/cypress/cypress/utils/testConfig.ts
  workspaces/frontend/src/__tests__/cypress/tsconfig.json
Labels: approved, lgtm, size/XXL, ok-to-test

#124 feat(ws): Notebooks 2.0 // Backend // List namespaces
  .github/workflows/controller-tests.yaml
  .github/workflows/ui-bff-build.yml
  workspaces/backend/README.md
  workspaces/backend/api/app.go
  workspaces/backend/api/namespaces_handler.go
  workspaces/backend/api/namespaces_handler_test.go
  workspaces/backend/api/workspacekinds_handler_test.go
  workspaces/backend/internal/models/namespaces.go
  workspaces/backend/internal/repositories/namespaces.go
  workspaces/backend/internal/repositories/repositories.go
Labels: approved, lgtm, size/L
