Repository kubeflow/notebooks, pull requests merged in 2024-05, with the labels that each got.

#1 add README and `.gitignore`
  .gitattributes
  .gitignore
  README.md
Labels: approved, size/M, lgtm

#2 Update README with warning about migration
  README.md
Labels: approved, lgtm, size/XS

#5 feat(ws): initial commit for controller
  .github/workflows/workspaces-controller_unit-tests.yaml
  workspaces/controller/.dockerignore
  workspaces/controller/.gitignore
  workspaces/controller/.golangci.yml
  workspaces/controller/Dockerfile
  workspaces/controller/Makefile
  workspaces/controller/PROJECT
  workspaces/controller/README.md
  workspaces/controller/api/v1beta1/groupversion_info.go
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/cmd/main.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/config/crd/kustomization.yaml
  workspaces/controller/config/crd/kustomizeconfig.yaml
  workspaces/controller/config/default/kustomization.yaml
  workspaces/controller/config/default/manager_config_patch.yaml
  workspaces/controller/config/default/manager_metrics_patch.yaml
  workspaces/controller/config/manager/kustomization.yaml
  workspaces/controller/config/manager/manager.yaml
  workspaces/controller/config/prometheus/kustomization.yaml
  workspaces/controller/config/prometheus/monitor.yaml
  workspaces/controller/config/rbac/kustomization.yaml
  workspaces/controller/config/rbac/leader_election_role.yaml
  workspaces/controller/config/rbac/leader_election_role_binding.yaml
  workspaces/controller/config/rbac/metrics_service.yaml
  workspaces/controller/config/rbac/role.yaml
  workspaces/controller/config/rbac/role_binding.yaml
  workspaces/controller/config/rbac/service_account.yaml
  workspaces/controller/config/rbac/workspace_editor_role.yaml
  workspaces/controller/config/rbac/workspace_viewer_role.yaml
  workspaces/controller/config/rbac/workspacekind_editor_role.yaml
  workspaces/controller/config/rbac/workspacekind_viewer_role.yaml
  workspaces/controller/config/samples/kustomization.yaml
  workspaces/controller/config/samples/v1beta1_workspace.yaml
  workspaces/controller/config/samples/v1beta1_workspacekind.yaml
  workspaces/controller/go.mod
  workspaces/controller/go.sum
  workspaces/controller/hack/boilerplate.go.txt
  workspaces/controller/internal/controller/suite_test.go
  workspaces/controller/internal/controller/workspace_controller.go
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
  workspaces/controller/test/e2e/e2e_suite_test.go
  workspaces/controller/test/e2e/e2e_test.go
  workspaces/controller/test/utils/utils.go
Labels: approved, lgtm, size/XXL

#7 feat(ws): initial commit for backend
  workspaces/backend/.gitignore
  workspaces/backend/Dockerfile
  workspaces/backend/Makefile
  workspaces/backend/README.md
  workspaces/backend/api/app.go
  workspaces/backend/api/errors.go
  workspaces/backend/api/healthcheck__handler_test.go
  workspaces/backend/api/healthcheck_handler.go
  workspaces/backend/api/helpers.go
  workspaces/backend/api/middleware.go
  workspaces/backend/cmd/main.go
  workspaces/backend/config/environment.go
  workspaces/backend/data/health_check_model.go
  workspaces/backend/data/models.go
  workspaces/backend/go.mod
  workspaces/backend/go.sum
Labels: approved, lgtm, size/XL
