Repository kubeflow/notebooks, pull requests merged in 2024-06, with the labels that each got.

#15 feat(ws): add kubernetes client to backend
  workspaces/backend/.dockerignore
  workspaces/backend/Dockerfile
  workspaces/backend/api/app.go
  workspaces/backend/cmd/main.go
  workspaces/backend/go.mod
  workspaces/backend/go.sum
  workspaces/backend/integrations/k8s.go
Labels: approved, lgtm, size/L

#6 feat(ws): add `Workspace` and `WorkspaceKind` CRD scaffolds
  workspaces/controller/PROJECT
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/go.mod
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
Labels: approved, lgtm, size/XXL

#16 feat(ws): update `Workspace` and `WorkspaceKind` definitions
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/go.mod
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
Labels: approved, lgtm, size/XXL

#17 chore: clean up OWNERS file (avoid non-maintainers)
  OWNERS
Labels: approved, lgtm, size/XS

#18 chore: clean up OWNERS file (avoid non-maintainers)
  OWNERS
Labels: approved, lgtm, size/XS

#19 feat(ws): initial commit for frontend
  .github/workflows/ui-bff-build.yml
  .github/workflows/ui-frontend-build.yml
  workspaces/backend/README.md
  workspaces/frontend/.gitignore
  workspaces/frontend/README.md
  workspaces/frontend/__mocks__/styleMock.js
  workspaces/frontend/jest.config.js
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/app/AppLayout/AppLayout.tsx
  workspaces/frontend/src/app/Dashboard/Dashboard.tsx
  workspaces/frontend/src/app/NotFound/NotFound.tsx
  workspaces/frontend/src/app/Support/Support.tsx
  workspaces/frontend/src/app/__snapshots__/app.test.tsx.snap
  workspaces/frontend/src/app/app.css
  workspaces/frontend/src/app/app.test.tsx
  workspaces/frontend/src/app/bgimages/.gitkeep
  workspaces/frontend/src/app/index.tsx
  workspaces/frontend/src/app/routes.tsx
  workspaces/frontend/src/app/utils/useDocumentTitle.ts
  workspaces/frontend/src/favicon.ico
  workspaces/frontend/src/index.html
  workspaces/frontend/src/index.tsx
  workspaces/frontend/src/typings.d.ts
  workspaces/frontend/stylePaths.js
  workspaces/frontend/tsconfig.json
  workspaces/frontend/webpack.common.js
  workspaces/frontend/webpack.dev.js
  workspaces/frontend/webpack.prod.js
Labels: approved, lgtm, size/XXL

#20 feat(ws): add `containerSecurityContext` to WorkspaceKind
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
Labels: approved, lgtm, size/XL
