Repository kubeflow/notebooks, pull requests merged in 2024-07, with the labels that each got.

#21 fix(ws): use correct `nodeSelector` type and add CRD validation tests
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
Labels: approved, lgtm, size/XL

#22 feat(ws): initial Workspace and WorkspaceKind controller loops
  workspaces/controller/Dockerfile
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/workspacekind_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/config/rbac/role.yaml
  workspaces/controller/config/samples/v1beta1_workspace.yaml
  workspaces/controller/config/samples/v1beta1_workspacekind.yaml
  workspaces/controller/internal/controller/suite_test.go
  workspaces/controller/internal/controller/workspace_controller.go
  workspaces/controller/internal/controller/workspace_controller_test.go
  workspaces/controller/internal/controller/workspacekind_controller.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
  workspaces/controller/internal/helper/helper.go
Labels: approved, lgtm, size/XXL

#24 chore(ws): remove unused libraries `react-axe` and `react-docgen-typescript-loader`
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/index.tsx
Labels: approved, lgtm, size/XXL, area/frontend, project/workspaces
