Repository kubeflow/notebooks, pull requests merged in 2025-03, with the labels that each got.

#213 feat(ws): add http service paths to WS get on backend
  workspaces/backend/internal/models/workspaces/funcs.go
  workspaces/backend/internal/models/workspaces/types.go
Labels: approved, size/M, lgtm, ok-to-test

#226 chore: issue templates + readme updates + common gha
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .github/ISSUE_TEMPLATE/02_feature_request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gh-workflow-approve.yaml
  .github/workflows/stale.yaml
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/L

#231 chore(ws): Upgrade vulnerable packages
  workspaces/frontend/package-lock.json
Labels: approved, size/M, lgtm, ok-to-test

#230 feat(ws): add `pendingRestart` field to workspace model
  workspaces/backend/internal/models/workspaces/funcs.go
  workspaces/backend/internal/models/workspaces/types.go
Labels: approved, size/M, lgtm, ok-to-test

#236 feat(ws): add initial workspace creation pod config step frontend
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationPodConfigSelection.tsx
Labels: approved, lgtm, size/S, ok-to-test

#238 feat(ws): Add MUI Theming Support for Workspace Creation
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/shared/style/MUI-theme.scss
Labels: approved, size/M, lgtm, ok-to-test

#241 feat(ws): add workspace creation image step frontend
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageFilter.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationKindSelection.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L, ok-to-test

#243 chore(ws): extract filter by labels component on workspace creation
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/labelFilter/FilterByLabels.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigSelection.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, size/M, lgtm, ok-to-test
