Repository kubeflow/notebooks, pull requests merged in 2025-02, with the labels that each got.

#161 feat(ws): Add "Connect" column to workspace table and display popup with workspace endpoints.
  workspaces/frontend/src/app/pages/Workspaces/WorkspaceConnectAction.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L

#193 fix(ws): handle empty pod metadata in controller
  workspaces/controller/internal/controller/workspace_controller.go
Labels: approved, lgtm, size/S

#195 feat(ws): introduce limits on HTTP body/header size
  workspaces/backend/api/app.go
  workspaces/backend/api/helpers.go
  workspaces/backend/api/middleware.go
  workspaces/backend/internal/server/server.go
Labels: approved, size/M, lgtm

#162 feat(ws): Implement Start restart and stop workspace actions
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRedirectInformationView.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRestartActionModal.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
Labels: approved, lgtm, size/XL

#202 feat(ws): add auth to backend
  workspaces/backend/api/app.go
  workspaces/backend/api/auth.go
  workspaces/backend/api/errors.go
  workspaces/backend/api/healthcheck_handler_test.go
  workspaces/backend/api/namespaces_handler.go
  workspaces/backend/api/namespaces_handler_test.go
  workspaces/backend/api/suite_test.go
  workspaces/backend/api/workspacekinds_handler.go
  workspaces/backend/api/workspacekinds_handler_test.go
  workspaces/backend/api/workspaces_handler.go
  workspaces/backend/api/workspaces_handler_test.go
  workspaces/backend/cmd/main.go
  workspaces/backend/go.mod
  workspaces/backend/go.sum
  workspaces/backend/internal/auth/authentication.go
  workspaces/backend/internal/auth/authorization.go
  workspaces/backend/internal/config/environment.go
  workspaces/backend/internal/helper/k8s.go
Labels: approved, lgtm, size/XL

#204 ci: trigger workflows for PRs with `ok-to-test` label
  .github/workflows/gh-workflow-approve.yaml
  .github/workflows/ws-backend-test.yml
  .github/workflows/ws-controller-test.yaml
  .github/workflows/ws-frontend-test.yml
Labels: approved, lgtm, size/L

#210 feat(ws): add `podTemplatePod` to Workspace status, for backend logs
  workspaces/controller/api/v1beta1/workspace_types.go
  workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
  workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
  workspaces/controller/internal/controller/workspace_controller.go
  workspaces/controller/internal/controller/workspacekind_controller.go
Labels: approved, lgtm, size/L, ok-to-test

#199 feat(ws): Notebooks 2.0 // Frontend // Workspaces details // Activity tab #171
  workspaces/frontend/src/__tests__/cypress/.gitignore
  workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/WorkspaceDetails/WorkspaceDetailsActivity.cy.ts
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsActivity.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/utilities/WorkspaceUtils.ts
Labels: approved, lgtm, size/L, ok-to-test

#197 feat(ws): Notebooks 2.0 // Frontend // Workspaces details // Pod template tab #173
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsPodTemplate.tsx
Labels: approved, lgtm, size/L, ok-to-test

#214 feat(ws): update JSON field names to camelCase in types and README.
  workspaces/backend/README.md
  workspaces/backend/internal/models/health_check/types.go
  workspaces/backend/internal/models/workspacekinds/types.go
  workspaces/backend/internal/models/workspaces/types.go
  workspaces/backend/internal/models/workspaces/types_create.go
Labels: approved, lgtm, size/L, ok-to-test
