Repository kubeflow/notebooks, pull requests merged in 2025-01, with the labels that each got.

#167 feat(ws): Fetch API Infra
  workspaces/frontend/jest.config.js
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/__mocks__/mockNamespaces.ts
  workspaces/frontend/src/__mocks__/styleMock.js
  workspaces/frontend/src/__mocks__/utils.ts
  workspaces/frontend/src/__tests__/unit/jest.d.ts
  workspaces/frontend/src/__tests__/unit/jest.setup.ts
  workspaces/frontend/src/__tests__/unit/testUtils/hooks.spec.ts
  workspaces/frontend/src/__tests__/unit/testUtils/hooks.ts
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/const.ts
  workspaces/frontend/src/app/context/NotebookContext.tsx
  workspaces/frontend/src/app/context/useNotebookAPIState.tsx
  workspaces/frontend/src/app/hooks/useNamespaces.ts
  workspaces/frontend/src/app/hooks/useNotebookAPI.ts
  workspaces/frontend/src/app/types.ts
  workspaces/frontend/src/shared/api/__tests__/errorUtils.spec.ts
  workspaces/frontend/src/shared/api/__tests__/notebookService.spec.ts
  workspaces/frontend/src/shared/api/apiUtils.ts
  workspaces/frontend/src/shared/api/errorUtils.ts
  workspaces/frontend/src/shared/api/notebookService.ts
  workspaces/frontend/src/shared/api/types.ts
  workspaces/frontend/src/shared/api/useAPIState.ts
  workspaces/frontend/src/shared/typeHelpers.ts
  workspaces/frontend/src/shared/utilities/const.ts
  workspaces/frontend/src/shared/utilities/useFetchState.ts
  workspaces/frontend/tsconfig.json
Labels: approved, lgtm, size/XXL

#154 feat(ws): add namespace dropdown to UI
  workspaces/frontend/src/__mocks__/mockNamespaces.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/NamespaceSelector.cy.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/NavSidebar.tsx
  workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
  workspaces/frontend/src/app/context/NotebookContext.tsx
  workspaces/frontend/src/app/hooks/useMount.tsx
  workspaces/frontend/src/app/types.ts
  workspaces/frontend/src/shared/api/__tests__/notebookService.spec.ts
  workspaces/frontend/src/shared/api/notebookService.ts
  workspaces/frontend/src/shared/components/NamespaceSelector.tsx
Labels: approved, lgtm, size/L

#160 feat(ws): Add popup to Workspace data vol column in workspaces table
  workspaces/frontend/src/app/pages/Workspaces/DataVolumesList.tsx
  workspaces/frontend/src/app/pages/Workspaces/ExpandedWorkspaceRow.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L

#174 feat(ws): Notebooks 2.0 // Frontend // Workspaces details // Live mockup
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsActions.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsOverview.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L

#184 feat(ws): Notebooks 2.0 // Frontend // Rename settings to debug
  workspaces/frontend/src/app/AppRoutes.tsx
  workspaces/frontend/src/app/pages/Debug/Debug.tsx
Labels: approved, lgtm, size/S

#157 feat(ws): add filter to workspaces table
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/__tests__/cypress/cypress.config.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/filterWorkspacesTest.cy.ts
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/components/Filter.tsx
Labels: approved, lgtm, size/XL

#178 feat(ws): implement delete workspace action with a confirmation popup
  workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/Workspaces.cy.ts
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/components/DeleteModal.tsx
Labels: approved, lgtm, size/L

#185 feat(ws): Notebooks 2.0 // Frontend // Workspace details // Applies MUI Theming
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsOverview.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/style/MUI-theme.scss
Labels: approved, size/M, lgtm

#134 fix(ws): update JSON payload for listing workspaces
  workspaces/backend/api/workspaces_handler_test.go
  workspaces/backend/internal/models/workspaces.go
  workspaces/backend/internal/repositories/workspaces.go
Labels: approved, lgtm, size/L

#187 chore(ws): Upgrade vulnerable packages
  workspaces/frontend/package-lock.json
Labels: approved, lgtm, size/S

#177 feat(ws): Notebooks 2.0 // Frontend // Workspaces table // Workspace Kind column #148
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/workspaceKind.cy.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaceKinds.mock.ts
  workspaces/frontend/src/app/actions/WorkspaceKindsActions.tsx
  workspaces/frontend/src/app/context/useNotebookAPIState.tsx
  workspaces/frontend/src/app/hooks/useWorkspaceKinds.ts
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/app/types.ts
  workspaces/frontend/src/shared/api/notebookService.ts
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L
