Repository kubeflow/notebooks, pull requests merged in 2025-06, with the labels that each got.

#399 feat(ws): added pod configs tab to workspace kind details
  workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetails.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsPodConfigs.tsx
Labels: approved, size/M, lgtm, ok-to-test

#401 fix(ws): Update Progress Stepper with UX feedback
  workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesSelection.tsx
  workspaces/frontend/src/shared/style/MUI-theme.scss
Labels: approved, lgtm, size/L, ok-to-test

#407 chore(ws): Upgrade vulnerable package webpack-dev-server
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
Labels: approved, lgtm, size/XL, ok-to-test

#408 fix(ws): Action Button Alignment and Jupyter Image Display
  workspaces/frontend/src/app/actions/WorkspaceKindsActions.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
Labels: approved, lgtm, size/XS, ok-to-test

#419 fix(ws): Expose active nav item on initial Workspaces page load
  workspaces/frontend/src/app/AppRoutes.tsx
  workspaces/frontend/src/app/NavSidebar.tsx
  workspaces/frontend/src/shared/style/MUI-theme.scss
Labels: approved, size/M, lgtm, ok-to-test

#414 chore(ws): enforce named imports for react hooks
  workspaces/frontend/.eslintrc.js
  workspaces/frontend/eslint-local-rules/no-react-hook-namespace.js
  workspaces/frontend/package.json
  workspaces/frontend/src/__tests__/unit/testUtils/hooks.spec.ts
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/AppRoutes.tsx
  workspaces/frontend/src/app/EnsureAPIAvailability.tsx
  workspaces/frontend/src/app/NavSidebar.tsx
  workspaces/frontend/src/app/components/ThemeAwareSearchInput.tsx
  workspaces/frontend/src/app/context/BrowserStorageContext.tsx
  workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
  workspaces/frontend/src/app/context/NotebookContext.tsx
  workspaces/frontend/src/app/context/useNotebookAPIState.tsx
  workspaces/frontend/src/app/error/ErrorBoundary.tsx
  workspaces/frontend/src/app/error/ErrorDetails.tsx
  workspaces/frontend/src/app/error/UpdateState.tsx
  workspaces/frontend/src/app/hooks/useGenericObjectState.ts
  workspaces/frontend/src/app/hooks/useNamespaces.ts
  workspaces/frontend/src/app/hooks/useNotebookAPI.ts
  workspaces/frontend/src/app/hooks/useWorkspaceCountPerKind.ts
  workspaces/frontend/src/app/hooks/useWorkspaceFormData.ts
  workspaces/frontend/src/app/hooks/useWorkspaceKindByName.ts
  workspaces/frontend/src/app/hooks/useWorkspaceKinds.ts
  workspaces/frontend/src/app/hooks/useWorkspaces.ts
  workspaces/frontend/src/app/pages/Debug/Debug.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/DataVolumesList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsActions.tsx
  workspaces/frontend/src/app/pages/Workspaces/ExpandedWorkspaceRow.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesVolumes.tsx
  workspaces/frontend/src/app/pages/Workspaces/WorkspaceConnectAction.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRedirectInformationView.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRestartActionModal.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
  workspaces/frontend/src/app/pages/notFound/NotFound.tsx
  workspaces/frontend/src/shared/api/useAPIState.ts
  workspaces/frontend/src/shared/components/ActionButton.tsx
  workspaces/frontend/src/shared/components/CustomEmptyState.tsx
  workspaces/frontend/src/shared/components/DeleteModal.tsx
  workspaces/frontend/src/shared/components/Filter.tsx
  workspaces/frontend/src/shared/components/NamespaceSelector.tsx
  workspaces/frontend/src/shared/utilities/useFetchState.ts
Labels: approved, lgtm, size/L, ok-to-test

#427 chore(ws): Upgrade vulnerable packages
  workspaces/frontend/package-lock.json
Labels: approved, lgtm, size/S, ok-to-test

#438 chore(ws): allowed theme configuration during frontend start
  workspaces/frontend/package.json
Labels: approved, lgtm, size/XS, ok-to-test

#439 chore(ws): show ESLint errors from local rules on IDE
  workspaces/frontend/.eslintrc.js
  workspaces/frontend/eslint-local-rules/index.js
  workspaces/frontend/eslint-local-rules/no-raw-react-router-hook.js
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/app/NavSidebar.tsx
  workspaces/frontend/src/app/hooks/useCurrentRouteKey.ts
  workspaces/frontend/src/app/routerHelper.ts
Labels: approved, lgtm, size/L, ok-to-test

#436 feat(ws): validate podMetadata for ws and wsk in webhook
  workspaces/controller/internal/webhook/suite_test.go
  workspaces/controller/internal/webhook/workspace_webhook.go
  workspaces/controller/internal/webhook/workspace_webhook_test.go
  workspaces/controller/internal/webhook/workspacekind_webhook.go
  workspaces/controller/internal/webhook/workspacekind_webhook_test.go
Labels: approved, lgtm, size/L, ok-to-test

#424 feat(ws): fix swagger warnings and only generate json output
  workspaces/backend/Makefile
  workspaces/backend/api/workspacekinds_handler.go
  workspaces/backend/api/workspaces_handler.go
  workspaces/backend/openapi/docs.go
  workspaces/backend/openapi/swagger.json
  workspaces/backend/openapi/swagger.yaml
Labels: approved, lgtm, size/XXL, ok-to-test

#450 chore: add OWNERS files with reviewers and labels
  .github/workflows/OWNERS
  workspaces/backend/OWNERS
  workspaces/controller/OWNERS
  workspaces/frontend/OWNERS
Labels: approved, lgtm, size/S, ok-to-test

#386 fix(ws): backend dockerfile
  workspaces/.dockerignore
  workspaces/backend/Dockerfile
  workspaces/backend/Makefile
Labels: approved, size/M, lgtm, ok-to-test

#361 chore: create issue templates for project planning
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/planning_epic.yml
  .github/ISSUE_TEMPLATE/planning_feature.yml
  .github/ISSUE_TEMPLATE/planning_task.yml
Labels: approved, lgtm, size/L, ok-to-test

#451 feat: refactor Form View to Edit only
  workspaces/frontend/src/app/pages/WorkspaceKinds/Form/WorkspaceKindForm.tsx
  workspaces/frontend/src/shared/api/apiUtils.ts
  workspaces/frontend/src/shared/api/backendApiTypes.ts
  workspaces/frontend/src/shared/api/notebookApi.ts
  workspaces/frontend/src/shared/api/notebookService.ts
Labels: approved, lgtm, size/L, area/frontend, area/v2, ok-to-test
