Repository kubeflow/notebooks, pull requests merged in 2025-05, with the labels that each got.

#217 feat(ws): add frontend hooks to call create WS backend
  workspaces/frontend/src/app/context/useNotebookAPIState.tsx
  workspaces/frontend/src/app/hooks/useCreateWorkspace.ts
  workspaces/frontend/src/app/pages/Workspaces/utils.ts
  workspaces/frontend/src/app/types.ts
  workspaces/frontend/src/shared/api/notebookService.ts
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L, ok-to-test

#306 fix(ws): Fix UI bugs in PF Theme
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/NavSidebar.tsx
  workspaces/frontend/src/app/const.ts
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/images/logo-dark-theme.svg
  workspaces/frontend/src/shared/components/Filter.tsx
Labels: approved, size/M, lgtm, ok-to-test

#262 feat(ws): Add properties tile to new workspace creation
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationPropertiesSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/properties/WorkspaceCreationPropertiesSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/properties/WorkspaceCreationPropertiesVolumes.tsx
  workspaces/frontend/src/shared/style/MUI-theme.scss
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L, ok-to-test

#315 feat(ws): workspaces connect button sizing
  workspaces/frontend/src/app/pages/Workspaces/WorkspaceConnectAction.tsx
Labels: approved, lgtm, size/XS, ok-to-test

#303 feat(ws): Notebooks v2 add secrets to workspace creation properties
  workspaces/frontend/src/app/pages/Workspaces/Creation/properties/WorkspaceCreationPropertiesSecrets.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/properties/WorkspaceCreationPropertiesSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L, ok-to-test

#326 fix(ws): filter chip label spacings
  workspaces/frontend/src/shared/style/MUI-theme.scss
Labels: approved, lgtm, size/XS, ok-to-test

#235 feat(ws): complete api swagger documentation across workspaces, namespaces, and workspacekinds
  workspaces/backend/api/helpers.go
  workspaces/backend/api/namespaces_handler.go
  workspaces/backend/api/workspacekinds_handler.go
  workspaces/backend/api/workspaces_handler.go
  workspaces/backend/openapi/docs.go
  workspaces/backend/openapi/swagger.json
  workspaces/backend/openapi/swagger.yaml
Labels: approved, lgtm, size/XXL, ok-to-test

#331 fix(ws): add secrets field to backend API schema
  workspaces/backend/api/workspaces_handler_test.go
  workspaces/backend/internal/models/workspaces/types.go
  workspaces/backend/internal/models/workspaces/types_create.go
  workspaces/backend/internal/repositories/workspaces/repo.go
  workspaces/backend/openapi/docs.go
  workspaces/backend/openapi/swagger.json
  workspaces/backend/openapi/swagger.yaml
Labels: approved, lgtm, size/L, ok-to-test

#313 feat(ws): Apply theme dependent components
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/filterWorkspacesTest.cy.ts
  workspaces/frontend/src/app/components/FormFieldset.tsx
  workspaces/frontend/src/app/components/ThemeAwareSearchInput.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/components/Filter.tsx
  workspaces/frontend/src/shared/style/MUI-theme.scss
Labels: approved, lgtm, size/L, ok-to-test

#346 feat(ws): prepare frontend calls to pause and start endpoints
  workspaces/frontend/src/app/context/useNotebookAPIState.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/ActionButton.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
  workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
  workspaces/frontend/src/shared/api/backendApiTypes.ts
  workspaces/frontend/src/shared/api/callTypes.ts
  workspaces/frontend/src/shared/api/notebookApi.ts
  workspaces/frontend/src/shared/api/notebookService.ts
  workspaces/frontend/src/shared/mock/mockNotebookService.ts
Labels: approved, lgtm, size/L, ok-to-test

#338 feat(ws): Add Empty State to Workspace list #259
  workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/components/CustomEmptyState.tsx
  workspaces/frontend/src/shared/components/Filter.tsx
Labels: approved, lgtm, size/XL, ok-to-test

#188 test(ws): Add workspaces tests
  workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/WorkspaceDetails/WorkspaceDetailsActivity.cy.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/Workspaces.cy.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspace.mock.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/WorkspaceDetailsActivity.cy.ts
  workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/Workspaces.cy.ts
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
Labels: approved, lgtm, size/L, ok-to-test

#364 fix(ws): update component structure to fix create ws button rendering
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/components/Filter.tsx
Labels: approved, lgtm, size/L, ok-to-test

#370 feat(ws): prepare frontend for Edit Workspace
  workspaces/frontend/src/app/AppRoutes.tsx
  workspaces/frontend/src/app/error/ErrorBoundary.tsx
  workspaces/frontend/src/app/hooks/useCurrentRouteKey.ts
  workspaces/frontend/src/app/hooks/useGenericObjectState.ts
  workspaces/frontend/src/app/hooks/useWorkspaceFormData.ts
  workspaces/frontend/src/app/hooks/useWorkspaceFormLocationData.ts
  workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsActions.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceFormDrawer.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/labelFilter/FilterByLabels.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesSecrets.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesVolumes.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/app/pages/notFound/NotFound.tsx
  workspaces/frontend/src/app/routerHelper.ts
  workspaces/frontend/src/app/routes.ts
  workspaces/frontend/src/app/types.ts
  workspaces/frontend/src/shared/api/backendApiTypes.ts
Labels: approved, lgtm, size/XL, ok-to-test

#341 feat(ws): Persist last used namespace across refreshes and tabs
  workspaces/frontend/src/app/App.tsx
  workspaces/frontend/src/app/context/BrowserStorageContext.tsx
  workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
  workspaces/frontend/src/shared/components/NamespaceSelector.tsx
Labels: approved, lgtm, size/L, ok-to-test

#387 feat(ws): Workspace Kind details drawer #252
  workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceDetailsOverview.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetails.tsx
Labels: approved, lgtm, size/L, ok-to-test
