Repository kubeflow/notebooks, pull requests merged in 2025-04, with the labels that each got.

#244 feat(ws): add workspace creation pod config step frontend
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigDetails.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigSelection.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L, ok-to-test

#250 chore(ws): add fork-ts-checker-webpack-plugin and fix typescript errors
  workspaces/frontend/config/webpack.common.js
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
  workspaces/frontend/src/app/context/NotebookContext.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/labelFilter/FilterByLabels.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigList.tsx
  workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigSelection.tsx
  workspaces/frontend/src/app/pages/Workspaces/ExpandedWorkspaceRow.tsx
  workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/L, ok-to-test

#256 feat(ws): retry failed reconciles much less aggressively
  workspaces/controller/cmd/main.go
  workspaces/controller/internal/controller/suite_test.go
  workspaces/controller/internal/controller/workspace_controller.go
  workspaces/controller/internal/controller/workspacekind_controller.go
  workspaces/controller/internal/controller/workspacekind_controller_test.go
  workspaces/controller/internal/helper/reconcile.go
Labels: approved, size/M, lgtm, ok-to-test

#258 chore(ws): Upgrade to Patternfly 6.2.0
  workspaces/frontend/package-lock.json
  workspaces/frontend/package.json
Labels: approved, lgtm, size/L, ok-to-test

#237 feat(ws): Notebooks 2.0 // Frontend // Workspace Kind Viewer // Live mockup #203
  workspaces/frontend/src/app/AppRoutes.tsx
  workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
  workspaces/frontend/src/shared/types.ts
Labels: approved, lgtm, size/XL, ok-to-test

#266 refactor(ws): Enhance "Create Workspace" Title Spacing
  workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
Labels: approved, lgtm, size/L, ok-to-test

#281 chore(ws): Upgrade vulnerable packages
  workspaces/frontend/package-lock.json
Labels: approved, lgtm, size/XS, ok-to-test
